server:
  port: 8081
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/projectdb?createDatabaseIfNotExsist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy : org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  application:
    name: project


